# Generated by Django 4.1.3 on 2022-11-22 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='DATE',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='DESCRIPTION',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='STATUS',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='TITLE',
            new_name='title',
        ),
    ]
