# Generated by Django 4.1.3 on 2022-11-22 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_date_todo_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('COMPLETED', 'COMPLETED'), ('INPROGRESS', 'INPROGRESS')], max_length=10),
        ),
    ]
